"""create progress history table

Revision ID: 1684643bf4ea
Revises: ef8d0591e4c7
Create Date: 2026-08-18 18:49:14.570697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1684643bf4ea'
down_revision: Union[str, Sequence[str], None] = 'ef8d0591e4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_history_id'), 'progress_history', ['id'], unique=False)
    op.create_index(op.f('ix_progress_history_task_id'), 'progress_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_history_task_id'), table_name='progress_history')
    op.drop_index(op.f('ix_progress_history_id'), table_name='progress_history')
    op.drop_table('progress_history')
    # ### end Alembic commands ###
