"""add status to progress history

Revision ID: c118e7bf384e
Revises: 1684643bf4ea
Create Date: 2026-08-18 19:00:54.001756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c118e7bf384e'
down_revision: Union[str, Sequence[str], None] = '1684643bf4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_history', sa.Column('status', sa.String(length=30), nullable=False))
    op.drop_column('progress_history', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_history', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('progress_history', 'status')
    # ### end Alembic commands ###
