"""add important and trash fields

Revision ID: c76363202e3c
Revises: 1d2d9aa4a1df
Create Date: 2026-08-18 21:47:18.918183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76363202e3c'
down_revision: Union[str, Sequence[str], None] = '1d2d9aa4a1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_important', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('tasks', 'is_important')
    # ### end Alembic commands ###
